# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.9"
  - "3.8"
  - "3.7"

before_install:
  - python -m pip install poetry

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - poetry install

# command to run tests, e.g. python setup.py test
script:
  - poetry run pytest